export default [
  {
    title: '4N',
    type: 'Website',
    techInfos: ['PHP, jQuery, skrollr.js'],
    imageUrl: '/images/projects/4N-w-logo-bnw.jpg',
    smallImageUrl: '/images/projects/small/4N-w-logo-bnw.jpg',
    url: 'http://4nparis.com',
    bgColor: '#111111',
    blendMode: 'lighten',
  },
  {
    title: 'Fractaleidoscope',
    type: 'Digital art',
    techInfos: ['python, arduino'],
    imageUrl: '/images/projects/fractaleidoscope-bnw.jpg',
    smallImageUrl: '/images/projects/small/fractaleidoscope-bnw.jpg',
    url: 'https://youtu.be/ghLG9gDp__A',
    bgColor: '#111111',
    blendMode: 'lighten',
  },
  {
    title: 'JMD',
    type: 'Website',
    techInfos: ['express.js'],
    imageUrl: '/images/projects/JMD-bnw.jpg',
    smallImageUrl: '/images/projects/small/JMD-bnw.jpg',
    url: 'http://jmd.paris',
    bgColor: '#111111',
    blendMode: 'lighten',
  },
  {
    title: 'Lou-Anne Lacaille',
    type: 'Website',
    techInfos: ['express.js'],
    imageUrl: '/images/projects/lacaille-2.jpg',
    smallImageUrl: '/images/projects/small/lacaille-2.jpg',
    url: 'http://www.lacaille-osteo-beaune.fr',
    bgColor: '#111111',
    blendMode: 'lighten',
  },
  {
    title: 'Datagif',
    type: 'Integration',
    techInfos: ['HTML, CSS (BEM), ES6, PHP'],
    imageUrl: '/images/projects/datagif-bnw.jpg',
    smallImageUrl: '/images/projects/small/datagif-bnw.jpg',
    url: 'https://datagif.fr',
    bgColor: '#111111',
    blendMode: 'lighten',
  },
  {
    title: 'inSynch',
    type: 'Game',
    techInfos: ['music composition, sound design'],
    imageUrl: '/images/projects/inSynch-bnw.jpg',
    smallImageUrl: '/images/projects/small/inSynch-bnw.jpg',
    url: 'http://www.themgames.net/insynch',
    bgColor: '#111111',
    blendMode: 'lighten',
  },
  {
    title: 'Bredrin Records',
    type: 'Webapp',
    techInfos: [
      'koa.js restful API, React.js,',
      'e-commerce, music composition',
    ],
    imageUrl: '/images/projects/BR02-bnw.jpg',
    smallImageUrl: '/images/projects/small/BR02-bnw.jpg',
    url: 'https://bredrinrecords.com',
    bgColor: '#111111',
    blendMode: 'lighten',
  },
  {
    title: 'Alors comment ça va ?',
    type: 'Blog',
    techInfos: ['wordpress'],
    imageUrl: '/images/projects/alorscommentcava-bnw.jpg',
    smallImageUrl: '/images/projects/small/alorscommentcava-bnw.jpg',
    url: 'http://alorscommentcava.fr',
    bgColor: '#111111',
    blendMode: 'lighten',
  },
  {
    title: 'PhD Thesis',
    type: 'Print',
    techInfos: ['LaTeX'],
    imageUrl: '/images/projects/phd-bnw.jpg',
    smallImageUrl: '/images/projects/small/phd-bnw.jpg',
    url: 'https://tel.archives-ouvertes.fr/THESES-UPMC/tel-01432887v1',
    bgColor: '#111111',
    blendMode: 'lighten',
  },
] satisfies Project[];
