export default [
  {
    type: 'front',
    content: [
      'Javascript',
      'ESM',
      'CSS',
      'Stylus',
      'Less',
      'Sass',
      'UnoCSS',
      'HTML5',
      'Pug',
      'Vue 2',
      'Vue 3',
      'Composition API',
      'Typescript',
      'Mapbox GL JS',
      'Turf.js',
      'Web workers',
      'Service workers',
      'SVG animation',
      'jQuery',
      'Functional programming',
      'Canvas',
      'WebGL',
      'Shaders',
      'SEO',
      'React',
    ],
  },
  {
    type: 'back',
    content: [
      'Node.js',
      'npm',
      'Fastify',
      'Express.js',
      'Koa.js',
      'Restful API',
      'MongoDB',
      'SSR',
      'PHP',
      'Go',
      'Wordpress',
      'SQL',
      'Letsencrypt',
      'e-commerce',
    ],
  },
  {
    type: 'build',
    content: [
      'ESM',
      'Babel',
      'Webpack',
      'Vite',
      'Esbuild',
      'Sourcemaps',
      'Grunt',
      'OOP',
      'Unit testing',
      'Jest',
      'Vitest',
      'PostCSS',
      'CI',
      'Concourse',
      'ytt',
    ],
  },
  {
    type: 'devops',
    content: ['Docker', 'Kubernetes'],
  },
  {
    type: 'methodology',
    content: ['BEM', 'Atomic Design', 'Agile', 'Pedagogy'],
  },
  {
    type: 'science',
    content: [
      'C',
      'C++',
      'Fortran',
      'Parallel computing',
      'MPI',
      'OpenMP',
      'Scientific programming',
      'Physics',
      'Data processing',
      'Signal processing',
      'Electronics',
      'Algorithmic',
      'Python',
      'Mathematica',
      'LaTeX',
    ],
  },
  {
    type: 'core',
    content: [
      'git',
      'MacOS',
      'Linux',
      'Raspberry',
      'Shell',
      'Bash',
      'Makefile',
      'Gnuplot',
      'vim',
      'Video compression',
    ],
  },
  {
    type: 'softwares',
    content: [
      'Photoshop',
      'Illustrator',
      'Sketch',
      'Figma',
      'Vscode',
      'Postman',
      'Lens',
    ],
  },
  {
    type: 'art',
    content: [
      'Music composition',
      'Sound design',
      'Digital art',
      'MIDI / OSC',
      'Arduino',
    ],
  },
  {
    type: 'languages',
    content: ['Fluent English', 'Medium Spanish'],
  },
] satisfies SkillsGroup[];
